language: ruby
rvm:
- 1.9.3
- 2.0.0
- 2.1.1
notifications:
  hipchat:
    rooms:
      secure: NdJU7VylZCGkGwLAz51DCxyvG5UaRBzsUlqkGIg3XkYoAjkHl/QJDljGURpCmPQfirJ9MN64XWKzgZVKB00O/C0ELZQ4No4f+lQMOWtdoyooT2D+HtgWusNpLLcHvHBlyct5hTT7qBbkxfQH+O8b3TX4uYUHfvPrB9hT66aO2g4=
