#            DO WHAT THE FUCK YOU WANT TO PUBLIC LICENSE
#                    Version 2, December 2004
#
# Copyright (C) 2011 ServeBox / http://www.servebox.org
#
# Everyone is permitted to copy and distribute verbatim or modified
# copies of this license document, and changing it is allowed as long
# as the name is changed.
#
#            DO WHAT THE FUCK YOU WANT TO PUBLIC LICENSE
#   TERMS AND CONDITIONS FOR COPYING, DISTRIBUTION AND MODIFICATION
#
#  0. You just DO WHAT THE FUCK YOU WANT TO.
#
# This program is free software. It comes without any warranty, to
# the extent permitted by applicable law. You can redistribute it
# and/or modify it under the terms of the Do What The Fuck You Want
# To Public License, Version 2, as published by Sam Hocevar. See
# http://sam.zoy.org/wtfpl/COPYING for more details.

roxanne:
  activation:
    days: [1, 2, 3, 4, 5]
    # Active from ~ 08:00 to 19:59
    timerange: !ruby/range 8..19
  consumers:
    jenkins:
      class: "Roxanne::Jenkins::JenkinsConsumer"
      host: "deadlock.netbeans.org"
      use_ssl: false
      disable_certificate_verification: false
      port: 80
      path: "/hudson/api/json"
  publisher:
    class: "Roxanne::IPX::IPXPublisher"
    host: "relayboard"
    username: ""
    password: ""
    use_ssl: false
    disable_certificate_verification: false
    port: 80
    path: "/preset.htm?led1=${1}&led2=${2}&led3=${3}&led4=0&led5=0&led6=0&led7=0&led8=0"
